### ISSUE TITLE
Is there any simple way to get all the using chunks which generated by same sender?

### ISSUE THREAD

**Issue by qclzdh** [eclipse-iceoryx/iceoryx#1038]
I am trying to find a way to get all the using chunks which is using by publisher and its subscribers, is there a simple to way to do this?
For example, there is one publisher and some subscirbers, which looked like this:
publisher_abc({"A", "B", "C"})
subscriber_1({"A", "B", "C"})
subscriber_2({"A", "B", "C"})
subscriber_3({"A", "B", "C"})
is there any API something like PublisherImpl::getCountOfUnReleasedChunksSenderByMyself() to get the number of exist chunks which include the chunksInUse of publisher_abc and the total chunks which is holding by subscriber_1,subscriber_2 and subscriber_3, and also the total number of chunks which are in the queue?

The reason i want to find this API is to limit the max holding chunks(include the chunk in the queue) of the same topic. One possible situation is server_abc has one publisher publisher_abc({"A", "B", "C"}), and there are other 100 process, one process has one subscriber_abs({"A", "B", "C"}), let's named this subscriber as subscriber_1, subscriber_2 ... subscriber_100. Let's think one special case, server will publish event(~10MByte) every 1 seconds, let's name this event as event_1, event_2 ... event_100, and subscirber_1 will hold event_1, subscirber_2 will hold event_2, subscirber_100 will hold event_100. So 100s later, 100 chunks will be held by this 100 process, at this case i want to deny the publihser to get more chunks to publish, how can i do this?

**Comment by qclzdh** [comment]
@elfenpiff  thanks for your answer, actually i didn't encouter this issue, we are just considering the worst cast which may happen in theory. If user release the chunk asynchronously, and you can't assume which chunk will be released first, at that case, this subscriber_N holding event_N is possible. It looks like both queueCapacity and block option are not a complete solution for this kind case.

**Comment by elfenpiff** [comment]
@budrus Do you have any insights here?

**Comment by budrus** [comment]
@qclzdh @elfenpiff There are many aspects you have to consider

1. polling access or waits/listener. If polling with what frequency?
2. queue capacities of subscribers
3. history capacity of publisher
4. Subscribers consume all the messages immediately, or store them for a longer time / for several iterations?
5. How long does a subscriber need to consume a single message?

I think it should be possible to calculate a worst case when all these parameters are known. Typically the worst case would be far away from reality but it would be a valid theoretical worst case. In your example with 1 publisher sending every second and 100 subscribers

1. lowest number of needed chunks is 1 when all the subscribers use a waits/listener and they manage to process and release the (same) message before the publisher allocates again
2. If the subscribing applications pull chunks at arbitrary times out of the queues and hold them for an arbitrary amount of time, the worst case should be the sum of all the chunks each subscriber can hold on user side (worst case all different ones) plus the largest queue size that is used plus the ones that are on publisher side. All the queues hold the latest samples according to the queue size. So I do not think it is valid to assume that the queues have different messages.

In the example above, if the 100 subscribers all consume different chunks, release this chunk before consuming the next one and have a queue size of 1, you would have 100 + 1 latest in the queues + 1 the new chunk that the publisher is just sending. I do not think that you can get a problem if you have 105 chunks.  Wanna bet @elfenpiff ?

@qclzdh your initial questions was how you can determine how  many chunks are currently used by a publisher and all the connected subscribers. You should be able to see this with the introspection if you ensure that only this publisher is using a specific mempool. You can do this by

1. Have the system running with only this publisher
2. Configure the mempools in a way that every publisher or at least the one interesting for you has its own mempool (By setting the mempool sizes according to sizeof() of your message) 

Then the introspection shows you with 1 sec updates the currently used number of chunks and it also shows you the maximum number of chunks that you needed since RouDi started. 
One best practice is to run the system in some kind of worst case mode and for a long time, then inspect the maximum numbers of chunk you needed, then maybe add some more for bad times and go with this. Sure the alternative is to calculate the worst case and configure this. This might be way more you ever need in real life

**Comment by mossmaurice** [comment]
Closing this issue. Feel free to re-open if there are further questions on this topic.
