### ISSUE TITLE
Create document on how to obtain a safety certificate for iceoryx

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1046]
## Brief feature description

Developer which are interested in a ASIL-D certificate for iceoryx may would like to know:
* Who they have to contact to purchase such a certificate
* When will such a certificate be available - rough timeline.
* What kind of features can they expect to use
* What iceoryx version (API) will be certified

This document should be easy accessible, directly linked on our website and linked in the beginning of our iceoryx github readme.

**Comment by mossmaurice** [comment]
@elfenpiff Thanks for creating the issue!

After some thinking, I concluded that most of the questions are out of scope for Eclipse iceoryx and should be answered by the product vendors using Eclipse iceoryx.

> Who they have to contact to purchase such a certificate

The [main readme](https://github.com/eclipse-iceoryx/iceoryx#where-is-eclipse-iceoryx-used) answers this with a table. We could add a sentence like "If you want to use iceoryx in a safety-related commercial product the code base alone is not enough, please contact one of the vendors and read  [this section](https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#quality-levels)". What do you think?

> When will such a certificate be available - rough timeline.

This should be answered on the individual product pages by the vendors and can't be answered for Eclipse iceoryx itself.

> What kind of features can they expect to use

Specific features of a commercial ISO26262 product are only know to the vendor and should also be part of the product which utilizes Eclipse iceoryx. A general overview over features is available in the [Kanban board](https://github.com/eclipse-iceoryx/iceoryx/projects/3). Should be maybe introduce a issue label `safety-releated`?

> What iceoryx version (API) will be certified

Same here, this depends on the vendor which offers a product based on Eclipse iceoryx.

**Comment by budrus** [comment]
@elfenpiff I agree with @mossmaurice. These are questions the Eclipse project cannot answer today, so closing this

**Comment by elBoberido** [comment]
@budrus maybe we should explicitly state this. After all, the questions arise and people might be confused since we talk about certification. I think the proposal of @mossmaurice would help here. We just need to state that the Eclipse project provides only the code but in order to use it in a safety critical environment one needs some additional stuff, e.g.

| Requirements for safety domain | Provider |
|--------------|------------|
| Code developed according well-established safety rules | Eclipse iceoryx project |
| Safety manual | Your friendly company around the corner |
| ... | ...|

I'm not sure if the Eclipse organization allows the promotion of companies but one could give the hint to look at the contributors

cc @elfenpiff
