### ISSUE TITLE
untyped subscriber bound to listener stalls, and scalability

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1109]
Hi, I've setup untyped subscribers to listeners from looking at the examples & reading the docs. 

The first 2570 messages go through from the publisher to the subscriber(s) just fine (single & multi process). Then the subscriber stalls for no apparent reason.  No more incoming data callbacks. 
-Any pointers as too why ? There are no delays our timeouts.

-I tried releasing the (publisher loan) memory in the listener registered callback, in case it would solve the above, to no avail. It triggers an error; kPOPO__CHUNK_RECEIVER_INVALID_CHUNK_TO_RELEASE_FROM_USER (51) .  I see a comment  _"// PRQA S 4127 1 # d'tor of SharedChunk will release the memory, we do not have to touch the returned chunk"_   -is it handled by the listener in this case ?

On a separate note I got somewhat concerned with the scalability of these listeners when I dug into the source code..
-I will have upto ~1000 parallelizable (lock/sync-free) "streams" with ~10 different callbacks / downstream handlers per stream. I solved it for now by multiplexing / partitioning to different listeners since they only take 128 callback each. The one background thread per listener & callback restriction will result in an explosion of kernel threads. -Should I maybe use a waitset here?    

Publishers are setup as;

      iox::capro::ServiceDescription service(
         to_iox<iox::capro::IdString_t>(topic.serviceId),
         to_iox<iox::capro::IdString_t>(topic.instanceId),
         to_iox<iox::capro::IdString_t>(topic.eventId),
         iox::capro::ServiceDescription::ClassHash{ 0U, 0U, 0U, 0U },
         iox::capro::Interfaces::INTERNAL);

      iox::popo::PublisherOptions publisherOptions;
      publisherOptions.historyCapacity = 10U;

Subscribers are setup as;

      iox::capro::ServiceDescription service(
         to_iox<iox::capro::IdString_t>(topic.serviceId),
         to_iox<iox::capro::IdString_t>(topic.instanceId),
         to_iox<iox::capro::IdString_t>(topic.eventId),
         iox::capro::ServiceDescription::ClassHash{ 0U, 0U, 0U, 0U },
         iox::capro::Interfaces::INTERNAL);

      iox::popo::SubscriberOptions subscriberOptions;
      subscriberOptions.queueCapacity = 10U;
      subscriberOptions.historyRequest = 5U;

**Comment by elfenpiff** [comment]
@niclar 
> Then the subscriber stalls for no apparent reason. No more incoming data callbacks.
-Any pointers as too why ? There are no delays our timeouts.

Without seeing the code I would suspect some kind of race condition. When you use the subscriber/publisher inside the listener callbacks you are not allowed to access them from the outside since all the ports are not thread safe.

> On a separate note I got somewhat concerned with the scalability of these listeners when I dug into the source code..

When we set the resource restrictions for the listener/waitset we just choose more or less a random number which seemed reasonable for us. But you can change this by hand in `iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp`.
The interesting numbers are:
* `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE` this restricts the listener/waitset in general to 128
* `MAX_NUMBER_OF_EVENTS_PER_LISTENER` must be less or equal to the previous value since every event acquires a notifier for a condition variable
* `MAX_NUMBER_OF_ATTACHMENTS_PER_WAITS` must be again less or equal to `MAX_NUMBER_OF_NOTIFIERS_PER_CONDITION_VARIABLE` since here also every attachment acquires a notification for a condition variable

When you set those numbers temporarily to 1000 or 2000 you should be fine with your use case. It maybe also useful to increase those numbers so that a user can attach in theory all ports (subscriber/publisher/server/client) to a waitset/listener. I added a todo to #1077 and if this does not block you I would start fixing this after our 2.0 code freeze (1st of march)

> Should I maybe use a waitset here?

I would try to favor the waitset over the listener. The reason is the implicit thread in the listener which can cause race conditions very easily since you are not always aware that you may access constructs from a different thread. With a waitset you start threads/concurrent task more explicitly when you need them.

**Comment by niclar** [comment]
@elfenpiff thanks for taking the time to answer. I don't think it's a race condition as described. I get the stall even when running one listener. If it helps, the subscriber / lisetner setup is as below;

   static void HandleSubscriptionDataReceived(iox::popo::UntypedSubscriber* subscriber, Intrabus::MessageCallback* callback)
   {
      subscriber->take().and_then([subscriber, callback](const void* msg)
      {
         (*callback)(msg);
      });
   }

void Intrabus::Register(const Topic& topic, MessageCallback callback, InternalSubscriberCallback subscriberCallback)
   {
      auto subscription = CreateSubscriber(topic);

      auto& it = m_runtime->m_subscribers.emplace_back(subscription, callback);

      m_runtime->GetListner(route(topic, m_listnerCapacity))
         .attachEvent(*subscription, iox::popo::SubscriberEvent::DATA_RECEIVED, iox::popo::createNotificationCallback(subscriberCallback, std::get<MessageCallback>(it)))
         .or_else([](iox::popo::ListenerError e)
         {
            std::cerr << "Intrabus - unable to attach subscriber, " << to_c_str(e) << ", exiting..." << std::endl;
            std::exit(EXIT_FAILURE);
         });
   }

**Comment by elfenpiff** [comment]
@niclar 

One possible issue I see is the following:
```cpp
      // the iterator may gets invalidated when you either remove an element before the iterator or you add an additional element with emplace_back and the vector has to reallocate the memory to another position
      auto& it = m_runtime->m_subscribers.emplace_back(subscription, callback); 

      m_runtime->GetListner(route(topic, m_listnerCapacity))
         .attachEvent(*subscription, iox::popo::SubscriberEvent::DATA_RECEIVED, 
 // here the iterator is captured in a callback, but it can be invalidated when during the runtime `m_runtime->m_subscribers` is changed
iox::popo::createNotificationCallback(subscriberCallback, std::get<MessageCallback>(it)))
         .or_else([](iox::popo::ListenerError e)
```

Maybe I do not understand the internal logic good enough but when you call `Register` multiple times or remove elements you may invalidate the iterators and either access the wrong subscriber in the vector or access a memory position which only contains the residuals of a former subscriber.
Both things would perfectly explain why your subscriber stalls, since you are not working on the actual subscriber anymore.

**Comment by niclar** [comment]
@elfenpiff re. the first comment;  it's not a vector it's a list, and it's guaranteed to have stable iterators so the above is safe.
Re. the second comment; that's true, but the subscribers are never removed though.

**Comment by elfenpiff** [comment]
@niclar happy to help!
