### ISSUE TITLE
Roudi console timestamps is out of date

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1130]
Looking at the Roudi console prinouts I see that the timestamps are wrong, why is that ?

I'm not using any config file for the Roudi..

E.g

←[0;90m1970-01-07 23:50:39.293 ←[0;1;93m[Warning]←[m: Received Keepalive

**Comment by elfenpiff** [comment]
@niclar This looks like a bug in our logger or our timing library 
@elBoberido do you have maybe an idea. 

At the moment we are in our hot release phase and I think we wont be able to fix this before the 28th of February.

**Comment by elBoberido** [comment]
@niclar do you have more information. We use `std::localtime();` to convert the timestamp from `std::chrono::high_resolution_clock::now()`. This was probably not the best idea since `high_resolution_clock` might be just an alias to `std::chrono::steady_clock`.

Could you check that on your system. If that is the case, It is fairly easy to switch to `std::chrono::system_clock`, which is recommended anyway.

**Comment by niclar** [comment]
In the the vs compiler stdlib has;    
using high_resolution_clock = steady_clock;
