### ISSUE TITLE
[iox-introspection-client] Error occurred while acquiring file lock named introspection

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1257]
I'm trying to introspect roudi using the iox-introspection-client but I encounter a permission error;

ls -all /tmp/introspection.lock
-rw------- 1 test test 0 Mar  9 09:18 /tmp/introspection.lock

ps -aux | grep roudi
root     2398422  0.1  0.2 257172 80736 ?        Sl   09:26   0:01 /opt/roudi/bin/iox-roudi -c /opt/roudi/etc/roudi/config.toml

sudo /opt/roudi/bin/iox-introspection-client --all
/iceoryx_hoofs/source/posix_wrapper/file_lock.cpp:53 { cxx::expected<FileLockError> iox::posix::FileLock::initializeFileLock() -> iox_open }  :::  [ 13 ]  Permission denied
permission to access file denied "/tmp/introspection.lock"
2022-03-09 09:28:22.517 [ Fatal ]: Error occurred while acquiring file lock named introspection
2022-03-09 09:28:22.518 [ Error ]: ICEORYX error! IPC_INTERFACE__COULD_NOT_ACQUIRE_FILE_LOCK
terminate called without an active exception
Aborted

**Comment by elfenpiff** [comment]
@niclar 

1. From your output it seems that the introspection client was started under the user `test` which created the lock file since a runtime name must be unique on the system. When you start now the introspection client as root the file lock prohibits root from running it again - which is correct!
2. It could also happen that the introspection client was running before and was somehow killed (with `SIGKILL`, see `kill -9`) and then we have a `lock` corpse sticking around.
Could you please remove the introspection lock with `sudo rm /tmp/introspection.lock` - then it should work again.

**Comment by niclar** [comment]
Removing the file did the trick, thanks!

**Comment by xchsh** [comment]
/home/YFCO/uxuxc170/workspace/beifen-0915/iceoryx-2.0.4/iceoryx_hoofs/source/posix_wrapper/file_lock.cpp:63 { iox::cxx::expected<iox::posix::FileLockError> iox::posix::FileLock::initializeFileLock() -> iox_flock }  :::  [ 89 ]  Function not implemented
open() not implemented for filesystem to "/var/lock/iox-cpp-subscriber-helloworld.lock"
2023-08-18 16:11:37.595 [ Fatal ]: Error occurred while acquiring file lock named iox-cpp-subscriber-helloworld
2023-08-18 16:11:37.595 [ Error ]: ICEORYX error! IPC_INTERFACE__COULD_NOT_ACQUIRE_FILE_LOCK
terminate called without an active exception
Abort (core dumped)

**Comment by elBoberido** [comment]
@xchsh what file system are you using? It seems it does not support file locking.

 I recall that we once had an issue on QNX where `/tmp` was mounted in a RAM disk with a filesystem which did not support file locking.
