### ISSUE TITLE
POPO__CHUNK_RECEIVER_INVALID_CHUNK_TO_RELEASE_FROM_USER

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1277]
## Required information

**Operating system:**
E.g. Ubuntu 16.04

**Compiler version:**
E.g. GCC 

**Observed result or behaviour:**
cyclonedds with iceoryx
**Expected result or behaviour:**
What do you expect to happen?
what is the err msg mean, It works seems all right
**Conditions where it occurred / Performed steps:**

**Comment by elfenpiff** [comment]
@sgf201 

To summarize: this is an error which should - in theory - only occur when using the C interface wrongly - the C++ interface would not allow such a behavior. It may be also a bug in iceoryx but for this I need to take a look at the code which is calling `iox_sub_release_chunk`.

In detail. When you are receiving a chunk with a subscriber in the C API with `iox_sub_take_chunk` you have to release it later to avoid memory leaks with `iox_sub_release_chunk`. But if you release the same chunk twice, aka. a double free, you will see such a warning.

You can reproduce it yourself very quickly when modifying the `iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c` so that `iox_sub_release_chunk` is performed twice, here the code snippet:
```c
while (ChunkReceiveResult_SUCCESS == iox_sub_take_chunk(subscriber, &userPayload))
{
    const struct RadarObject* sample = (const struct RadarObject*)(userPayload);
    printf("%s got value: %.0f\n", APP_NAME, sample->x);
    fflush(stdout);
    iox_sub_release_chunk(subscriber, userPayload);
    iox_sub_release_chunk(subscriber, userPayload); // this double release leads to your error
}
```

Since double free's and memory leaks are common problems in C I would start looking there. A bug in iceoryx is less likely but since we lack some tests for this particular behavior in our subscriber tests it is possible that a little screw up is still hiding there. 

We have to add further tests either way in iceoryx for those classes and test this behavior. Maybe we reveal something in the process.

**Comment by sgf201** [comment]
I USE cyclonedds with iceoryx, and processes are forked out ,some msgs lost which sent by another process in another host

**Comment by sgf201** [comment]
https://github.com/eclipse-cyclonedds/cyclonedds/issues/1105

**Comment by sgf201** [comment]
does the memory leak make roudi holds less mem blocks? if there is not any mem block what will happen?

**Comment by elfenpiff** [comment]
The issue you reported seems to be not a memory leak but a double free. 

But in general memory leaks will decrease the amount of available memory blocks and when RouDi does not have enough memory left the publisher is unable to send data since it can no longer acquire memory chunks.
The error which is then reported is `MEPOO__MEMPOOL_GETCHUNK_POOL_IS_RUNNING_OUT_OF_CHUNKS`

**Comment by sgf201** [comment]
1，the reason of "data loss" find ,the data is not send

2，in cyclonedds ,if loan failed, cyclonedds will sleep 1ms,then try again, if there is no more chunk, loan function will be trapped,
    while (1)
    {
      enum iox_AllocationResult alloc_result = iox_pub_loan_chunk(wr->m_iox_pub, (void **) &ice_hdr, chunk_size);
      if (AllocationResult_SUCCESS == alloc_result)
        break;
      // SHM_TODO: Maybe there is a better way to do while unable to allocate.
      //           BTW, how long I should sleep is also another problem.
      dds_sleepfor (DDS_MSECS (1));
    }
but i think return err is good than traped

**Comment by sgf201** [comment]
> The issue you reported seems to be not a memory leak but a double free.
> 
> But in general memory leaks will decrease the amount of available memory blocks and when RouDi does not have enough memory left the publisher is unable to send data since it can no longer acquire memory chunks. The error which is then reported is `MEPOO__MEMPOOL_GETCHUNK_POOL_IS_RUNNING_OUT_OF_CHUNKS`

Is there easy way to check or record chunk number of roudi when roudi is running

**Comment by sgf201** [comment]
@elfenpiff

**Comment by elfenpiff** [comment]
@sgf201 Yes there is, you can use the iceoryx introspection. To build iceoryx with introspection create the cmake files with:
```sh
cd iceoryx
cmake -Bbuild -Hiceoryx_meta -DINTROSPECTION=ON
```

and compile
```sh
cd build
make -j10
```

Now you can start the introspection client with
```
./iox-introspection-client --all
```

And with `--help` you get some more infos about the other options.
