### ISSUE TITLE
32 bit build failure 

### ISSUE THREAD

**Issue by BhanuKiranChaluvadi** [eclipse-iceoryx/iceoryx#1379]
I am trying to compile iceorxy as a part of ros2 packages. I had no problem compiling it to a 64 bit binary but 32-bit build fails. (I am using isar / bitbake tasks to compile iceorxy as a part of a bigger process) 

## Required information

**Operating system:**
Linux 704089e4662c 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 GNU/Linux

**Compiler version:**
gcc (Debian 8.3.0-6) 8.3.0

**Observed result or behaviour:**
```
Failed <<< iceoryx_hoofs [3.43s, exited with code 2]

/home/builder/ros-humble-world/src/iceoryx/iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp:32:43: error: static assertion failed: A RelativePointerData must be placed on an address which does not cross the native alignment!
32 | static_assert(sizeof(RelativePointerData) == alignof(RelativePointerData),
```

I am guessing, the problem on 32-bit is
```
sizeof(RelativePointerData) = 8
alignof(RelativePointerData) = 4

```

And thing of adding `-fpack-struct=8 `   flag to the build step

**Comment by mossmaurice** [comment]
@BhanuKiranChaluvadi Thanks for reporting this issue!

As mentioned in the [docs](https://iceoryx.io/v2.0.2/getting-started/installation/) iceoryx does currently not support 32-bit systems. 

>
> Dependencies
> 
>   64-bit hardware (e.g. x86_64 or aarch64; 32-bit hardware might work, but is not supported)
> ..snip..

Would it be feasible for you to switch to a 64-bit architecture? If not, could you imagine to contribute 32-bit support? Note upfront: I might be a hard task because of some [lock-free data structures](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_hoofs/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp).

**Comment by mengkeat** [comment]
What are the other issues for 32-bit support ? I do not know the code base or related problem well, but a brief glance seems to be on the counter on the size being atomic 64 bit ? I am considering doing this also in support of my work which has some requirements for Iceoryx for 32-bit hardware. Thanks !

**Comment by elfenpiff** [comment]
@mengkeat 

> What are the other issues for 32-bit support ?

The problem is that our lock-free queues will not work with 32-bit because of the counter you discovered. In more detail we put the ABA-counter and sometimes read-write position in one single 64-bit number and with 32-bit we run into serious restrictions. 

If you nevertheless use it you got a problem since the code is no longer lock-free and works with process-local mutex (STL fallback). But it is essential for us that we use inter-process mutex in such an environment, something standard C++ cannot offer us.

So the solution would be to implement a queue for you, which is not lock-free but uses a inter-process mutex right from the beginning. This wouldn't be as efficient as a lock-free algorithm and also be unusable in a safety-critical environment but would work for 32-bit.
