### ISSUE TITLE
Disable monitoring (keepalive messages) at compile time

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1380]
## Brief feature description

Sending keepalive messages over unix domain sockets in a background thread of every running application can cause jittering as discussed here: #1374 

A additional CMake switch to disable this feature for every application and in roudi itself solves the jittering. The compile time switch should disable:
* the background thread in roudi receiving and handling this message
* the background thread in every application sending this message
* disable the monitoring feature for roudi completely.

A runtime solution would be also be possible but then every application would require an additional parameter while initializing the runtime to disable monitoring. This seems like more code to write and a public API adjustment therefore I would favor the compile time approach.

## Relates

#1361

**Comment by elfenpiff** [comment]
Analysis showed that in `posh_runtime_impl.cpp` the sending of the keepalive message in `PoshRuntimeImpl::sendKeepAliveAndHandleShutdownPreparation` caused the problem.

**Comment by elBoberido** [comment]
@elfenpiff disabling the whole thread on the application is not easily possible since this thread is also used to unblock block publisher/subscriber on shutdown if the `QUEUE_FULL_POLICY` is set to block.

Just disabling the transmission via unix domain sockets would be fine but writing a timestamp to a shm region dedicated for each process would also be a good temporary solution.
