### ISSUE TITLE
PoshRuntime and all IpcChannels must be thread-safe

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1405]
## Brief feature description

A completely valid use case is to create multiple threads in an application and to create in those threads ports, listeners or waitsets.
All those object will call the `PoshRuntime` to acquire a resource. Since this is absolutely hidden from the user no one can be aware that here concurrency issues may arise. Even notes and warnings in documentation will not prevent this.

So we have two options, we have to ensure that the `PoshRuntime` is completely thread-safe or we redesign the `PoshRuntime` so that it becomes an actual shared memory resource factory which it already is.

## Detailed information

* The thread-safety could be easily ensured with the `smart_lock`.
* I would favor a redesign so that our API would look a bit more like to `ROS2` API. Then it would be clear that a runtime creates those shared memory resources and it would enable us to connect to two different roudi instances which may becomes handy for mixed-critical setups.

**Comment by elfenpiff** [comment]
cc @elBoberido @budrus

**Comment by elBoberido** [comment]
@elfenpiff the `PoshRuntime` is already thread-safe. Currently this is done by manually locking a mutex. For the IpcChannels, this is not required since the `PoshRuntime` is already guarded by a mutex and AFAIK we don't have a shared state in the abstractions and `sendto` is MT-safe (have to check this).

Just for clarification. I'm not advocating against such an API change

**Comment by elBoberido** [comment]
@elfenpiff can we close this issue or rephrase it? With the current title it leaves the impression that we have a threading issue, which is not the case.
