### ISSUE TITLE
Build error on certain versions of Windows/Visual Studio

### ISSUE THREAD

**Issue by clalancette** [eclipse-iceoryx/iceoryx#1476]
Originally reported at https://github.com/ros2/ros2/issues/1284 by @chample:

## Required information

**Operating system:**
E.g. Windows 10 Pro Version 21H2, OS build 19044.1766

**Compiler version:**
E.g. Visual Studio 2019

**Observed result or behaviour:**
Following step by step guide: https://docs.ros.org/en/humble/Installation/Alternatives/Windows-Development-Setup.html#build-the-ros-2-code

Abstracts of build log:
"\ros2_humble\src\eclipse-iceoryx\iceoryx\iceoryx_posh\source\roudi\process_manager.cpp(186,94): error C2001: newline in constant"

**Expected result or behaviour:**
Successful compilation

**Conditions where it occurred / Performed steps:**
Compile with certain versions of Visual Studio 2019.

As additional information, we do *not* see this problem on the nightly ROS 2 CI builds: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2356/ .  So there must be something specific to the particular platform/setup.

**Comment by dkroenke** [comment]
Hello @chample,
this issue comes up when the Windows locale settings doesn't support `UTF-8` properly.
It would be interesting to know which locale language is configured on Windows system level. You can check this opening the `Language settings` -> `Administrative language settings` -> `Language for non-Unicode programs`.

As a test you can set this to `English (United States)` and restart Windows, then do a clean build for ROS 2 again.
The tutorial for the windows build of ROS 2 requires that the locale language needs to support `UTF-8` 
like `English (United States)`.

If you are on a up-to-date Windows version you may see the option `Beta: Use Unicode UTF-8 for worldwide language support` in the language menu for locale. This option enabled helps here too for resolving this issue without changing the system locale language.

CC @clalancette
