### ISSUE TITLE
Refactor `static_storage` to return pointers wrapped in `cxx::optional`

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1672]
## Required information

**Operating system:**
Ubuntu 20.04.1

**Compiler version:**
GCC 8.4.0

**Observed result or behaviour:**
`static_storage::allocate()` does return `T*` so users have to check for `nullptr` which can easily be forgotten

**Expected result or behaviour:**
`static_storage::allocate()` shall return `cxx::optional<T*>` so users have to check for a valid pointer more explicitly

**Comment by elfenpiff** [comment]
@mossmaurice I am a big fan of the `optional` but an allocator is such a low level construct that I would keep the current syntax. Especially, since an `optional` would make this allocator incompatible with every other allocator existing in the whole C++ ecosystem.
Just think of `malloc`, `new`, the allocator concept from C++23: https://en.cppreference.com/w/cpp/memory/allocator , the type of allocator every container requires if one would like to use a polymorphic allocator or an allocator as part of the type.

In the end we would end up providing an allocator which no one can use. So please return here a pointer and the `nullptr` check has to be performed by the user. Furthermore, the allocator should never be used directly, it is always part of an abstraction which handles such cases so that the end user is never confronted with it.

**Comment by elfenpiff** [comment]
@MatthiasKillat

**Comment by elfenpiff** [comment]
@mossmaurice Btw. your solution does not solve the problem.

See this rephrased sentence from your original observed behavior:
`static_storage::allocate()` does return `cxx::optional<T*>` so users have to check for `nullopt` which can easily be forgotten

**Comment by mossmaurice** [comment]
> Especially, since an optional would make this allocator incompatible with every other allocator existing in the whole C++ ecosystem.

That's a good point. I was torn between from the beginning on this topic. Shall we document this somewhere that API closeness is preferred for low-level constructs?

**Comment by elfenpiff** [comment]
> That's a good point. I was torn between from the beginning on this topic. Shall we document this somewhere that API closeness towards the STL is preferred for low-level constructs?

No, I would not mention this anywhere and would not consider this a risk at all since the statement:
`X` does return `optional/expected` so users have to check for `value` which can easily be forgotten

Is valid for every method/function which returns this.
