### ISSUE TITLE
Use Zero-Copy receive in all IPC-Channel types and the posh IPC channel

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1693]
## Brief feature description

Instead of using an API with an additional copy like:
```cxx
 cxx::expected<std::string, IpcChannelError> receive()
```

the user could provide a preallocated object like `iox::vector` or `iox::string` where the received message is directly written into to avoid the additional copy. Like
```
cxx::expected<IpcChannelError> receive(cxx::vector<BUFFER_SIZE>& buffer);
```

## Tasks

- [ ] add API for `iox::string`
- [ ] add API for `iox::vector`

**Comment by elBoberido** [comment]
@lucabart97 once you are done with the `string` this would be the feature to integrate the `iox::string` into the `UnixDomainSocket` and the other IPC channels.

**Comment by lucabart97** [comment]
What type of ```iox::vector```? ```char```? ```uint8_t```?

**Comment by elBoberido** [comment]
@lucabart97 with C++17 there is another option with `std::byte`. I think `std::byte*` can easily be casted to an `uint8_t*` or `char*` and removes the ambiguity of being interpreted as a C string.

**Comment by lucabart97** [comment]
what is the next step? 👀
You want also the ```iox::vector``` or I could move to the next interface that need the ```iox::string``` to avoid dynamic memory creation at runtime?

**Comment by elBoberido** [comment]
No, the `iox::vector` can be done later. You can move to the next interface. I'm currently not quite sure which one it is but be aware, once you use the new `UnixDomainSocket` API, Windows will not work since it uses the `NamedPipe` as `IpcChannel`. You need to also implement the API for the `NamedPipe` and `MessageQueue` since they can be configured to be used as `IpcChannel`.
