### ISSUE TITLE
Nifty counter for PoshRuntimeImpl

### ISSUE THREAD

**Issue by nnmm** [eclipse-iceoryx/iceoryx#1725]
## Brief feature description

The `PoshRuntimeImpl` is a static variable (Meyer's singleton). When used with Cyclone DDS, sometimes (unfortunately) there are other static objects containing a DDS entity (e.g. domain participant), which on destruction uses the `PoshRuntime`. The destruction order of these static variables is impossible to predict, so it would be good to have a way to extend the lifetime of the `PoshRuntimeImpl` with reference-counting until its last use, as a short-term fix.

In the long term, a better solution might be to eliminate this singleton altogether, but that's not the focus of this issue.

## Detailed information

It was proposed by @elfenpiff to use the [nifty counter idiom](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Nifty_Counter) to implement refcounting for `PoshRuntimeImpl`.

**Comment by elBoberido** [comment]
@nnmm this seems to be somehow related to our `ScopedStatic`. Maybe it could be consolidated with the nifty couter idiom. AFAIK, for our use case the `Initializer` for the `PoshRuntime` must have a static lifetime else the `PoshRuntime` would be destroyed immediately after the `initRuntime` call. So there would be the static `PoshRuntime` initialized via placement new and the static `Initializer`. In addition we need a way to duplicate the `Initializer` in order to extend the lifetime past the static `Initializer`.

Without a static `Initializer`, this would behave exactly like the `ScopeGuard` of the `ScopedStatic`.

In the long run we indeed want to get rid of the singleton in order to e.g. be able to communicate with multiple RouDis from the same process.

**Comment by nnmm** [comment]
@elBoberido Thanks for the pointer.

My understanding is that the standard nifty counter from the link above already has a static initializer. Every translation unit that includes `posh_runtime.hpp` would get a copy of that static initializer, and because it comes _before_  any static variable `X` from the cpp file that's currently compiled, the initializer and thus the `PoshRuntime` will only be destroyed after `X`, making it safe for `X` to (indirectly) depend on `PoshRuntime`.

Then, we would need to include that header in `rclcpp/default_context.cpp` and maybe other places that have static variables that indirectly depend on the `PoshRuntime`, if any. It's not pretty, but I believe it's the only idea we currently have.

**Comment by nnmm** [comment]
We could also create a new header, `extend_posh_runtime_lifetime.hpp` to convey the intent more clearly.

**Comment by nnmm** [comment]
What's not clear to me yet is whether we can keep the `setRuntimeFactory()` functionality with the nifty counter, because the initialization of `PoshRuntime` will happen eagerly, not lazily like before. So the runtime will usually already be created by the time `setRuntimeFactory()` is called.

**Comment by elBoberido** [comment]
@nnmm I just skimmed over the page behind the link. Probably I didn't fully get it. Anyway, it would be great if it works. I'm just wondering if there are issues with shared libraries and of course also the problem with `setRuntimeFactory` which is used for testing purposes. Maybe the whole stuff needs to be refactored.

**Comment by nnmm** [comment]
I think I found a way to do it. But `posh_runtime_single_process.cpp` puzzles me. It looks like you're derefencing a nullptr in `singleProcessRuntimeFactory()` – what is this supposed to do?

**Comment by elBoberido** [comment]
@elfenpiff `posh_runtime_single_process` is your little baby. Maybe you can help :) 

cc @nnmm
