### ISSUE TITLE
Fix variant alignment

### ISSUE THREAD

**Issue by FerdinandSpitzschnueffler** [eclipse-iceoryx/iceoryx#1742]
## Brief feature description

The `variant` has an array `m_storage` as member which has the maximal size of its alternative types and is aligned to the maximal alignment of its alternative types. What happens when the type with the biggest size is not the type with the biggest alignment? Can this lead to errors? Can we fix this if we align the array size to the maximal alignment?

## Tasks

- [x] Clarify if this is a problem -> no problem
- [ ] ~~Fix if needed~~

**Comment by FerdinandSpitzschnueffler** [comment]
^^ @elfenpiff @elBoberido

**Comment by MatthiasKillat** [comment]
We have to determine both, maximum size `MS` and maximum alignment `MA` at compile time. This can be done  with various techniques and is at least already done with the size otherwise it is already broken.

Assuming we have those we have two options:
1. align the buffer with any alignment but compensate by increasing the size `S = MS + MA` (worst case assumption with buffer alignment 1, can be reduced if alignment is restricted).
2. align the buffer to `A = MA` and `S = MS`

In case 1. we need to be careful when constructing a concrete type T with alignment TA (so we cannot always construct into the buffer at the beginning). This is a disadvantage as it makes the emplace logic more complicated. This can still be done at compile time, it is e.g. done in the `static_storage` which does not know the possible types to be stored in advance (unlike variant).

In case 2. we can always construct to the beginning (but restrict the object more). This works because all alignments are powers of two and hence divide the maximum alignment. The disadvantage is restricted alignment of the buffer.

I think we should go with alternative 2.

Then we can use `using storage = std::aligned_storage<SA, MA>::type` as a buffer and should not need to change (much?) existing logic . Using `UninitializedArray` is not advised here, we do not need the array access logic and the element type would have to be something like `storage` anyway: `UninitializedArray<storage, 1>`.

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler short answer: It is not a problem and does not need a fix

long answer: see https://github.com/eclipse-iceoryx/iceoryx/issues/1742#issuecomment-1284255200 :)

medium answer: alignment is only an issue if it is less than the required alignment for a type, i.e. a `uint64_t` must be placed at an address which is a multiple of 8 and an `uint32_t` to an address which is a multiple of 4. Since the latter is always fulfilled for an alignment of the former this is not an issue. The problem arises only if you place an `uint64_t` at an address which is aligned to an `uint32_t` since half of the time the address would be be aligned wrong. And as @MatthiasKillat already mentioned, alignment is always a power of 2.

**Comment by FerdinandSpitzschnueffler** [comment]
@MatthiasKillat @elBoberido Thanks for the clarification! I close this ticket since no fix is needed.
