### ISSUE TITLE
dds_write crash in ThreadSafePolice

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1790]
## Required information

**Operating system:**
E.g. Ubuntu 16.04

![image](https://user-images.githubusercontent.com/5253415/202078385-d6346df6-a8c0-46b2-b509-4a7860b3b51e.png)
crash when send chunk
cyclonedds link
https://github.com/eclipse-cyclonedds/cyclonedds/issues/1481

**Comment by elfenpiff** [comment]
@sgf201 thanks for the bug report. For the time being I would wait until the cyclone dds side has made some debugging and analysis before proceeding with this bug report. If it turns out that this originated really in iceoryx I would take it from there but in my opinion the best approach is to analyse it from top to bottom and start with cyclone dds.

If nothing is happening in the next week please ping me again then I would try to look at it.

**Comment by elBoberido** [comment]
@sgf201 do you have the output from the terminal where RouDi runs? I think the application did not send the heartbeat in time and RouDi might have assumed that the application died and cleaned up the resources which invalidated a mutex. You can start RouDi with `-m off` to disable the monitoring. In this case the heartbeat signal is not evaluated and the cleanup only happens when RouDi shuts down or when the exact same application tries to register at RouDi again.

**Comment by sgf201** [comment]
> 



> @sgf201 do you have the output from the terminal where RouDi runs? I think the application did not send the heartbeat in time and RouDi might have assumed that the application died and cleaned up the resources which invalidated a mutex. You can start RouDi with `-m off` to disable the monitoring. In this case the heartbeat signal is not evaluated and the cleanup only happens when RouDi shuts down or when the exact same application tries to register at RouDi again.

![image](https://user-images.githubusercontent.com/5253415/202484242-764d5868-394c-4bbb-97e0-871aae391af6.png)
writer app stderr print those sentence.
a little confuse about cleaned up the resources which invalidated a mutex
I think the mutex instance is init by writer ,how could roudi which is running seperatly cleaned up the mutex?

**Comment by sgf201** [comment]
instead of disable the monitoring,can I change the heartbeat time required?

**Comment by elBoberido** [comment]
do you have a similar log message in the RouDi terminal
```
2022-11-17 19:33:07.007 [Warn ]: Application iox-cpp-user-header-publisher not responding (last response 1537 milliseconds ago) --> removing it
```
This would confirm my theory.

Unfortunately the heartbeat timeout cannot be changed via parameter and one would need to change the source code.

There is a mutex in the publisher itself. It is usually uncontested, only when new subscriber are added there is contention.

**Comment by sgf201** [comment]
> do you have a similar log message in the RouDi terminal
> 
> ```
> 2022-11-17 19:33:07.007 [Warn ]: Application iox-cpp-user-header-publisher not responding (last response 1537 milliseconds ago) --> removing it
> ```
> 
> This would confirm my theory.
> 
> Unfortunately the heartbeat timeout cannot be changed via parameter and one would need to change the source code.
> 
> There is a mutex in the publisher itself. It is usually uncontested, only when new subscriber are added there is contention.
![image](https://user-images.githubusercontent.com/5253415/202843293-c8fe948b-b3db-4891-b838-ebdb270ac71b.png)
do you accept this judgment? I think there are two different sign between the two crash. 1.in 1643 it rease segment fault ,but in1790 it rease sigabort 2.in 1790 the writer is alive and do not plan to exit
![image](https://user-images.githubusercontent.com/5253415/202843280-0501eb87-85fe-4a83-be34-8cd506ad92c7.png)

**Comment by sgf201** [comment]
@elBoberido

**Comment by elBoberido** [comment]
@sgf201 I do not have enough knowledge about the Cyclone DDS codebase in order to make any assessment. I think it is best to wait till that PR is merged and see whether the bug still occurs.
