### ISSUE TITLE
"seperate roudi server"Is it possible?

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1840]
## Brief feature description

seperate roudi server

## Detailed information

E.g. a list of pros and cons of different considerations and how iceoryx and its user could benefit from it
for server may crash, a idea comes up, is it possible?
1. each dds progress raise a roudi server ,and truncks  are only used for this program
2. reader can get data without communicating to the roudi server

**Comment by elfenpiff** [comment]
@sgf201 I do not understand your question completely.

RouDi is a daemon and per se not a service which a server provides. Even in a safety critical environment we have to rely on roudi otherwise shared memory communication would not be possible at the moment (but I do not state that this is carved in stone for the future).

It is possible that roudi crashes and the whole system goes down. But this should be very unlikely for the following reasons:
* roudi is very well tested (but still something can slip through)
* roudi does not allocate resources at runtime, only at startup time. This means bugs which are involved in allocating/deallocating resources can be excluded since it does not happen. This is an important point since most bugs occur while handling resources.

With that being said, I think when roudi crashes it is likely on the startup phase (when services cannot yet be created or connected).

Does it somehow answer your issue?

**Comment by sgf201** [comment]
Roudi crashed sometimes
![image](https://user-images.githubusercontent.com/5253415/211752533-bc52fe51-70ea-420d-84cb-88e9ac4d8e49.png)

**Comment by sgf201** [comment]
In addition, I would like to ask whether it is possible for each process to allocate a set of memory and send it to the receiver for use, so that the crash of one process will not cause problems for other processes, and can also reduce inter-process communication
Actually, I want to ask a sub-question, is it possible for the reader to get the real buf content without communicating with roudi after receiving the chunk information by cyclonedds

**Comment by elfenpiff** [comment]
@sgf201 Internally we currently have a proof of concept and planing a potential redesign of iceoryx. This would also address some issues you mentioned here like: "process allocates memory" instead of roudi and the system is stable and running even without roudi.

I think in February we have a plan and have a design document describing upcoming changes. I would add you there so that you are up to date and also can review it with your use case in mind.

But here are some more details to your questions:

> possible for each process to allocate a set of memory and send it to the receiver for use

This is not so easy. You could use our posix shared memory object to create your own shared memory segment and send the details over to the other process which than maps the shared memory into its process space. But then you have re implemented roudi functionality. Furthermore, it introduces a lot of additional problems you have to handle. What about when the application crashes? How is thread-safety ensured? How is the memory synchronized between processes? Are the constructs you use there even inter-process capable?
So I would strongly refrain from this approach but with the upcoming refactoring it is maybe indirectly possible or happening behind the scenes.
 
 > is it possible for the reader to get the real buf content without communicating with roudi
 
 No. But this may changes with the upcoming refactoring.
 
 To your bug:
 > Roudi crashed sometimes
 
The error `POPO__CHUNK_DISTRIBUTOR_CLEANUP_DEADLOCK_BECAUSE_BAD_APPLICATION_TERMINATION` can only occur when a application either dies due to a fatal error like a segmentation fault or is killed with the signal `SIGKILL` while holding the mutex of the chunk distributor.
In either way, this is caused by a fatal error inside the user application. To fix this issue you could try to explore why the application dies fatally.
 * do you kill it with something like `kill -9 ${APPLICATION_PID}`?
 * is it crashing due to some bug?
 * were all resources cleaned up before your system started?

**Comment by sgf201** [comment]
thanks so much for answers, especially for the potential redesign infomation

    do you kill it with something like kill -9 ${APPLICATION_PID}?
were all resources cleaned up before your system started?
yes the test case  is designed to kill user program by kill -9 for many times, and it is seems right for roudi health test for that server should not crash when user program take any accepted action, e.g killed by kill -9

    is it crashing due to some bug?
the bug means bug in user program or bug in roudi?  the message point out that roudi crashed for deadlock, I am confusing about the dead lock.
    were all resources cleaned up before your system started
roudi  restart at begin of this test case

**Comment by elfenpiff** [comment]
@sgf201 I think the easy fix to your problem is to kill all iceoryx applications with `kill -TERM` so that they are able to cleanly deregister at roudi and clean up all resources.

**Comment by sgf201** [comment]
> @sgf201 I think the easy fix to your problem is to kill all iceoryx applications with `kill -TERM` so that they are able to cleanly deregister at roudi and clean up all resources.

thanks  but first, the case is designed by others 
second, I also think that the applications do not share lock instance to roudi , so roudi should not crash whether application clean up resources. about deregister I know that roudi will remove it after 1.5s for no heartbeat

**Comment by elBoberido** [comment]
@sgf201 there is some activity but currently there is no ETA when this will officially be supported ... it at all

**Comment by elBoberido** [comment]
Closing this issue since it is a duplicate of #1129
