### ISSUE TITLE
vector.erase() has a wrong code.

### ISSUE THREAD

**Issue by luojian1983** [eclipse-iceoryx/iceoryx#1842]
## Required information

**Operating system:**
All

**Compiler version:**
All

**Observed result or behaviour:**
In code file "iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl":
```cxx
inline bool vector<T, Capacity>::erase(iterator position) noexcept
{
    if ((begin() <= position) && (position < end()))
    {
        uint64_t index{static_cast<uint64_t>(position - begin())};
        size_t n{index};
        **// ===> The wrong line should move to here.**
        while ((n + 1U) < size())
        {
            at(n) = std::move(at(n + 1U));
            ++n;
        }
        **at(n).~T(); // ===> This line should move to the line before while. or the wrong element will be destructed.**
        m_size--;
        return true;
    }
    return false;
}
```

**Expected result or behaviour:**
Result will be undefined.

**Conditions where it occurred / Performed steps:**
Every time call erase() of vector.

**Comment by elfenpiff** [comment]
@luojian1983 I double checked the tests and the implementation here and I think you are mistaken here. But let me deep dive into the implementation.

When I would apply your solution and call `at(n).~T()` before the loop the element would be completely destroyed and we only have naked memory left at this position. Every subsequent call to this object would be undefined behavior.

So the line `at(n) = std::move(at(n + 1U));` would be undefined behavior in the first iteration.

Now lets take a look at the algorithm. 
1. When `position` is the last element then the while loops condition fails and is never run. Only `at(n).~T()` is called which is what we want.
2. When `position` is not the last element, for instance 2 in a container of 4 elements.
  * `n = 2`
  * we move element `3` to position `2` in the first loop iteration, `n = 3`
  * we move element `4` to position `3` in the second loop iteration, `n = 4`
  * after the loop we delete the element at position `n = 4` since every element was moved one step to the right and this element is no longer needed.

So from this perspective the algorithm looks fine.

When you take a look at the file `test_cxx_vector.cpp` one can observe that we test exactly those cases with their side effects. See the following test names:
* EraseFailsWhenElementIsInvalid
* ErasingElementDecreasesSize
* EraseOfLastElementCallsDTorOnly
* EraseOfMiddleElementCallsDTorAndMove
* EraseOfFrontElementCallsDTorAndMove
* EraseMiddleElementDataCorrectAfterwards (verifies that the content is correct)
* EraseFrontElementDataCorrectAfterwards
* EraseLastElementDataCorrectAfterwards
* EraseLastElementOfFullVectorDataCorrectAfterwards

Internally, we have even further and more generic tests which are also verifying the correctness in even greater detail.

So this should make a bug unlikely but still I may overlook something!

@luojian1983 could you maybe provide me a simple code snippet which may cause the bug you are suspecting. Or could you provide me a more detailed explanation why you think this is flawed?

**Comment by elBoberido** [comment]
@elfenpiff I think the issue might be when the dtor does things slightly different than the move assignment, e.g. notifying someone about the destruction. Technically the element at `n` is destroyed not at `position`

**Comment by elBoberido** [comment]
@elfenpiff you could delete the element at `position` and then use the placement new move constructor at this position. Then all the following elements can be moved and the last moved from element can be destroyed

**Comment by elfenpiff** [comment]
@elBoberido I agree when the dtor somehow relies on the `this` pointer this seems off and your solution could solve the problem.
On the other hand it comes at a cost.
* suddenly we call the destructor of 2 elements, the element at the erase position and the last element. The of behavior of the dtor would still exist but would now be at the last position.
* we have an additional move construction on the erase position
* we require that the type has the move constructor implemented to call erase.

And it looks like that the STL vector behaves in this case exactly like our vector, see this code snippet:
```cxx
#include <iostream>
#include <vector>
void __log(void* t, const char* msg) {
    std::cout << "this = " << std::hex << t << " ::: " << msg << std::endl;
}
#define log() __log(this, __PRETTY_FUNCTION__)
struct A {
    A() noexcept { log(); }
    ~A() noexcept { log(); }
    A(const A&) { log(); }
    A(A&&) { log(); }
    A& operator=(const A&) {
        log();
        return *this;
    }
    A& operator=(A&&) {
        log();
        return *this;
    }
};
int main() {
    std::cout << "Create\n\n";
    std::vector<A> sut;
    std::cout << "Resize\n\n";
    sut.resize(5);
    std::cout << "Erase\n\n";
    sut.erase(sut.begin() + 2);
    std::cout << "Destroy\n\n";
    return 0;
}
```

Compiled with `g++ code.cpp -lc++` or `g++ code.cpp -lstdc++` the behavior seems always the same:

```
Create

Resize

this = 0x55743d7292c0 ::: A::A()
this = 0x55743d7292c1 ::: A::A()
this = 0x55743d7292c2 ::: A::A()
this = 0x55743d7292c3 ::: A::A()
this = 0x55743d7292c4 ::: A::A()
Erase

this = 0x55743d7292c2 ::: A &A::operator=(const A &)
this = 0x55743d7292c3 ::: A &A::operator=(const A &)
this = 0x55743d7292c4 ::: A::~A()
Destroy

this = 0x55743d7292c0 ::: A::~A()
this = 0x55743d7292c1 ::: A::~A()
this = 0x55743d7292c2 ::: A::~A()
this = 0x55743d7292c3 ::: A::~A()
```

You see that erase of the 3rd element moves the 4th element to position 3 and the 5th element to position 4 and it removes the last element.

@luojian1983 could you please confirm that this was the issue?

**Comment by luojian1983** [comment]
@elfenpiff Thanks for focus on this problem. I don't confirm whether understand your meaning, so I comment it again, I think it's an easy bug, and I have checked it with our team.

template <typename T, uint64_t Capacity>
inline bool vector<T, Capacity>::erase(iterator position) noexcept
{
    if ((begin() <= position) && (position < end()))
    {
        uint64_t index{static_cast<uint64_t>(position - begin())};
        size_t n{index};
        while ((n + 1U) < size()) // will break always when "n == size() - 1", that is the last element's position.
        {
            at(n) = std::move(at(n + 1U));
            ++n;
        }
        at(n).~T(); // it always destroy the last element, but you want to destroy the element at position. So it's wrong.
        m_size--;
        return true;
    }
    return false;
}

**Comment by luojian1983** [comment]
@elfenpiff Sorry, it's my wrong, the code is correct.. sorry sorry..

**Comment by elfenpiff** [comment]
@luojian1983 No problem. Happens to me all the time ;)
