### ISSUE TITLE
iox+dds together working issue

### ISSUE THREAD

**Issue by woshiyunsk** [eclipse-iceoryx/iceoryx#1908]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
GCC 9.4.0

**Eclipse iceoryx version:**
branch v2.0.3

**Observed result or behaviour:**
when iox and dds working together on two machines in the same net, if a particanpant restart, the communication can not recover again(unless restarting other participant)

**Expected result or behaviour:**
the participant exit and restart soon ,the communication should be recover soon.

**Conditions where it occurred / Performed steps:**
1,machine A: iox-roudi, iox-dds-gateway, /iceoryx_examples/icedelivery/iox-cpp-publisher(gateway start before publisher)
2,machine B: iox-roudi, iox-dds-gateway, /iceoryx_examples/icedelivery/iox-cpp-subscriber
3,exit the publisher(on A), and restart soon, the communication can not recover（unless restart the gateway on machine A)
4,exit the gateway on machine B, and restart soon, the communication can not recover(unless restart the subscriber)
5, some times the issue may not appears, this is because the variable m_isRunning.store(true) the function runMultithreaded(), which is in gateway_generic.inl,  may not work when the child thread discoverLoop and forwardLoop creating.
6,a deeper analysising find that the subsriber is not in the subscriber list when the publisher restart.(after adding debug info)
7,more info, the "break" in the for cycle in the sendToAllMatchingSubscriberPorts() in port_manager.cpp，generate the issue.
8,when I change the "break" to "continue", the issue is no longer exist .
9,but another issue is appear: when I add a publisher on machine B, the subscirber will receive the topic from publisher on the machine B twice.
10,when I exit the gateway on machine B, it can receive only one.
11,so, I guess, the twice topic may, one is go by iceoryx, the other one is go by dds(local).

**Comment by elfenpiff** [comment]
@woshiyunsk Thanks for reporting the issue. Sadly I have to tell you that we moved the iceoryx_dds_gateway out of the core iceoryx repository since only very few people used it actually.
But in general we still support it and when we release iceoryx 3.0 we try to ensure that it still works with the dds gateway.

Now to your report.

> 8,when I change the "break" to "continue", the issue is no longer exist .

It sounds like a fix. Could you create a PR with it then we could merge it to iceoryx master. I just think since you discovered and solved a part of the issue you should be also the person who receives appreciation for it.
To create a PR you have to:
 * sign the ECA (eclipse committer agreement)
 * start every commit with `iox-#1908` so that we can trace it back to this issue
 * let the PR title start with `iox-#1908`
 
 When this is done we could also merge it to the 2.0 release branch, see: https://github.com/eclipse-iceoryx/iceoryx/tree/release_2.0 so that it is available for you in iceoryx 2.0 directly.

> 11,so, I guess, the twice topic may, one is go by iceoryx, the other one is go by dds(local).

Your guess is correct and we already knew the issue but it requires some refactoring to solve it. This year a huge refactoring of iceoryx is pending with a new and shiny architecture. I will add this issue to our list of requirements we have to consider.

For the moment, would this behavior be acceptable for you? Maybe you have a way to work around this? If this is a dealbraker for you I would try to investigate it further.

**Comment by woshiyunsk** [comment]
> @woshiyunsk Thanks for reporting the issue. Sadly I have to tell you that we moved the iceoryx_dds_gateway out of the core iceoryx repository since only very few people used it actually. But in general we still support it and when we release iceoryx 3.0 we try to ensure that it still works with the dds gateway.
> 
> Now to your report.
> 
> > 8,when I change the "break" to "continue", the issue is no longer exist .
> 
> It sounds like a fix. Could you create a PR with it then we could merge it to iceoryx master. I just think since you discovered and solved a part of the issue you should be also the person who receives appreciation for it. To create a PR you have to:
> 
> * sign the ECA (eclipse committer agreement)
> * start every commit with `iox-#1908` so that we can trace it back to this issue
> * let the PR title start with `iox-#1908`
> 
> When this is done we could also merge it to the 2.0 release branch, see: https://github.com/eclipse-iceoryx/iceoryx/tree/release_2.0 so that it is available for you in iceoryx 2.0 directly.
> 
> > 11,so, I guess, the twice topic may, one is go by iceoryx, the other one is go by dds(local).
> 
> Your guess is correct and we already knew the issue but it requires some refactoring to solve it. This year a huge refactoring of iceoryx is pending with a new and shiny architecture. I will add this issue to our list of requirements we have to consider.
> 
> For the moment, would this behavior be acceptable for you? Maybe you have a way to work around this? If this is a dealbraker for you I would try to investigate it further.

@elfenpiff Thanks for your reply and invitation to creat a PR, I will try it later.
According to your reply, my guess is correct,  then ,in my understanding, this may need to be resolved in dds, by refusing message from local, to ensure the full-duplex of the iceoryx+cyclonedds system, then participants, about same topic can be deployed on different machines freely.

**Comment by woshiyunsk** [comment]
@elfenpiff Thanks for your reply and invitation to creat a PR, I will try it later.
According to your reply, my guess is correct,  then ,in my understanding, this may need to be resolved in dds, by refusing message from local, to ensure the full-duplex of the iceoryx+cyclonedds system, then participants, about same topic can be deployed on different machines freely.
