### ISSUE TITLE
MAX_GROUP_NAME_LENGTH should be at least equal to MAX_USER_NAME_LENGTH

### ISSUE THREAD

**Issue by atirehgram** [eclipse-iceoryx/iceoryx#1919]
## Required information

**Operating system:**
Any supported

**Compiler version:**
Any supported

**Eclipse iceoryx version:**
`master`

**Observed result or behaviour:**
Since by default `adduser`/`useradd` add the user to a group with the same name as the new user's login name (see [the docs](https://linux.die.net/man/8/adduser)), any user with a login name longer than 16 characters cannot run RouDi out of the box without changing their group settings (which they might not want to/be allowed to do). Since longer login names are allowed (up to `32` chars), longer group names should also be allowed (also up to `32` chars).

Edit: `groupadd` [documentation](https://linux.die.net/man/8/groupadd) also mentions `32` chars as the limit.

**Expected result or behaviour:**
Everyone can happily run RouDi out of the box. To this goal, `MAX_GROUP_NAME_LENGTH` should be set to `32` here: https://github.com/eclipse-iceoryx/iceoryx/blob/b10cc415c9ccf0d00d84681e2560d5636e61fb30/iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp

**Conditions where it occurred / Performed steps:**
- Make a new user with login name `0myname.mysurname` (17 chars), without specifying any group, so that it will be added to the default group `0myname.mysurname`
- Run RouDi with default configuration: `./iox-roudi`
- You will get this error message: `[Error]: Error: Could not find group "0myname.mysurnam"` (notice that the last character has been truncated).

**Comment by elfenpiff** [comment]
@atirehgram Thank you for the detailed and well-researched report!  Happens sadly not to often.

You found something where I struggled a lot when we implemented this.

So in general you are right, the group and user name in linux have a maximum supported length of `32` according to the linux `add{user|group}` man page. 
But if you ask via `sysconf` the underlying posix system how long a login name can be (`LOGIN_NAME_MAX`) you most likely will get a length of 256, see (https://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html) (which somehow corresponds to a user name) 

If you look at `adduser` in FreeBSD you see a maximum supported user name length of `16`, see https://man.freebsd.org/cgi/man.cgi?adduser(8).

And I think even in Fedora it once had a length of 16.

So my thought was to use the minimum user/group name length which is supported on all platforms which iceoryx supports (Windows, Linux, QNX, FreeBSD ...) but with your issue here I think it was a mistake.

Changing it at the place where you proposed may now lead to weird surprises and bugs on platforms where the max supported name length is smaller.

 My suggestion would be to solve this in the iceoryx platform layer (the first section in there provides a rough idea about it: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/custom-iceoryx-platform.md) which we introduced to handle exactly this kind of platform specific settings. So we define the maximum user/group name length for each platform and then use this setting to define the maximum supported length in `posix_access_rights.hpp`.

So in every platform (`linux`, `mac`, `qnx`, `unix`, `win`) under `iceoryx_platform` you have to add the two variables
* `constexpr uint64_t MAX_USER_NAME_LENGHT = ??;`
* `constexpr uint64_t MAX_GROUP_NAME_LENGTH = ??;`
in the file `iceoryx_platform/PLATFORM/include/iceoryx_platform/platform_settings.hpp`.

Then you can use this in `posix_access_rights.hpp` by including `iceoryx_platform/platform_settings.hpp` and access the values via `platform::MAX_??_NAME_LENGTH`. For now I would set the value to `32` on linux and `16` for the rest since it is the minimum which every platform supports.

I could implement it in the way I described it but since you discovered the issue I would give the preference to you when you would like to fix it.
So please let me know if you would like to turn this into your first contribution.

**Comment by atirehgram** [comment]
@elfenpiff Thank you for the feedback! It looks like a good solution, although in the future it might make more sense to use group IDs instead of names to avoid these problems.

I followed the instructions in `CONTRIBUTING.md` but when I try to push my branch I get an error message that I do not have the correct access rights. Is there anything I'm missing?

**Comment by elfenpiff** [comment]
@atirehgram I think we have to add some further instructions to the `CONTRIBUTING.md`. Usually, you work iceoryx and then create a new branch on your fork with the prefix `iox-#1919` to link to this issue.

When you are finished with the changes you create a pull request from your branch onto iceoryx master.
