### ISSUE TITLE
broken build: std::result_of is removed in C++20

### ISSUE THREAD

**Issue by niclar** [eclipse-iceoryx/iceoryx#1934]
-Can you make the usage of the now deprecated and removed std::result_of conditional on the C++ revision. C++2x builds are now broken.

HEAD: adbed1ba3a415e6b051cac37f13f01c9e9d10e3e

**Comment by elBoberido** [comment]
@niclar I think this is easy to fix. It should be possible to add a language version switch in `iceoryx_platform/linux/include/iceoryx_platform/platform_settings.hpp` similar to what is done in `iceoryx_platform/linux/include/iceoryx_platform/attributes.hpp`. I might also be a good idea to move the `invoke_result` alias somewhere else since it is a bit out of place in `platform_setting.hpp`

@elfenpiff @mossmaurice Objections? Ideas?

**Comment by niclar** [comment]
as a temporary workaround one can override the removal as;

if(WIN32)
    add_compile_definitions(_HAS_DEPRECATED_RESULT_OF)
else()
    add_compile_definitions(_LIBCPP_ENABLE_CXX20_REMOVED_TYPE_TRAITS)
endif()

**Comment by elBoberido** [comment]
@niclar sure, but we already have the machinery to use `invoke_result` for C++17 and above. No need to rely on deprecated functionality on newer C++ standards. We just have to do the same we did with `attributes.hpp` and add a language version switch. On macOS and Windows we already use `std::invoke_result`.

Would you like to implement this?
