### ISSUE TITLE
Roudi service logs redirected to file

### ISSUE THREAD

**Issue by YeahhhhLi** [eclipse-iceoryx/iceoryx#1937]
## Brief feature description

I can't seem to find a configuration for log redirection

```txt
iox-roudi --version                                                                                                                                       
RouDi version: 2.0.2
Build date: 2023-03-06T12:00:52Z
Commit ID: 
```
I hope that the logs produced by roudi can be output to a certain file to facilitate troubleshooting

**Comment by elBoberido** [comment]
@YeahhhhLi oh, you can of course always run `./iox-roudi 2>&1 | tee roudi-log.txt`

**Comment by YeahhhhLi** [comment]
> @YeahhhhLi oh, you can of course always run `./iox-roudi 2>&1 | tee roudi-log.txt`

Thanks! 
I thought about this solution before, but the best thing is to use the officially supported way. Looking at it now, this is a short-term solution. 

I will consider customized roudi services later.

**Comment by elBoberido** [comment]
@YeahhhhLi closing the issue since there are two options to achieve your goals
- `./iox-roudi 2>&1 | tee roudi-log.txt`
- build your own RouDi and use the mechanism described in https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/design/logging.md#creating-a-custom-logger to use a custom logger
