### ISSUE TITLE
xenomai can used by c api ?

### ISSUE THREAD

**Issue by guojun08512** [eclipse-iceoryx/iceoryx#1979]
## Required information

**Operating system:**
xenomai
version: 5.15.51
**Compiler version:**
gcc version 10.3.0

**Eclipse iceoryx version:**
v2.0.2

**Observed result or behaviour:**
/home/conan/w/prod/BuildSingleReference/.conan/data/iceoryx/2.0.2/_/_/build/53d5f0e565104166f721ce6bd8d7cf8bc275295a/source_subfolder/iceoryx_hoofs/source/posix_wrapper/thread.cpp:27 { void iox::posix::setThreadName(pthread_t, const ThreadName_t&) -> iox_pthread_setname_np }  :::  [ 0 ]  Success
This should never happen! Success
Condition: false && "internal logic error" in iox::posix::setThreadName(pthread_t, const ThreadName_t&)::<lambda(auto:1&)> [with auto:1 = iox::posix::PosixCallResult<int>] is violated. (/home/conan/w/prod/BuildSingleReference/.conan/data/iceoryx/2.0.2/_/_/build/53d5f0e565104166f721ce6bd8d7cf8bc275295a/source_subfolder/iceoryx_hoofs/source/posix_wrapper/thread.cpp:31)
2023-04-24 15:29:58.603 [ Error ]: ICEORYX error! EXPECTS_ENSURES_FAILED
terminate called without an active exception

**Conditions where it occurred / Performed steps:**
[Demo](https://github.com/eclipse-iceoryx/iceoryx/blob/v2.0.2/iceoryx_examples/request_response_in_c/client_c_basic.c)
panic

**Comment by elfenpiff** [comment]
@guojun08512 I do not know the OS xenomai, is this an android variant? 

I think the problem lies in the non-posix (np) `pthread_setname_np`. One easy way to fix this is to implement this function as a stub on your platform and just return 0 - for success.

But this has the disadvantage that the threads name is not set which can become a pain during debugging - nevertheless the system should be running.

If the platform where you are on supports to set names for threads you could also use inside the platform abstraction the native call and model the `pthread_setname_np` behavior with the native API. See this: https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html

**Comment by guojun08512** [comment]
**xenomai** it's linux realtime os
@elfenpiff  thanks, I'll give it a try

**Comment by guojun08512** [comment]
@elfenpiff I solved the problem with dynamic linking.
Thank you for the insight.
