### ISSUE TITLE
Bug in 'ListenerImpl'

### ISSUE THREAD

**Issue by qclzdh** [eclipse-iceoryx/iceoryx#2137]
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Eclipse iceoryx version:**
master

**Observed result or behaviour:**
process crashed

**Expected result or behaviour:**
process run normally

**Conditions where it occurred / Performed steps:**
change the examples as following, and then run it
```
diff --git a/iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp b/iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
index e25cc5856..871a93432 100644
--- a/iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
+++ b/iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
@@ -76,10 +76,11 @@ int main()
 {
     iox::runtime::PoshRuntime::initRuntime(APP_NAME);
 
+std::cout << "test ListenerImpl " << std::endl;
     // the listener starts a background thread and the callbacks of the attached events
     // will be called in this background thread when they are triggered
     //! [create listener]
-    iox::popo::Listener listener;
+    iox::popo::ListenerImpl<10> listener;
     //! [create listener]
 
     //! [create heartbeat and subscribers]

```

**Comment by elBoberido** [comment]
Indded, there is an issue in the `ListenerImpl` when used directly but it is not meant to use directly. Only the `Listener` itself is public API. The `ListenerImpl` was created to try to fix an issue with the C binding which in the end did not work and should have been reverted.

Why exactly do you want to use the `ListenerImpl` instead of the `Listener`?
