### ISSUE TITLE
iox-roudi is not found

### ISSUE THREAD

**Issue by JackieesLiao** [eclipse-iceoryx/iceoryx#2153]
When I run the daemon process ./iox-roudi on the terminal, it prompts that the file or directory iox-roudi is not found. What should I do?
![屏幕截图 2024-01-05 143115](https://github.com/eclipse-iceoryx/iceoryx/assets/88898152/e8d86c0f-aa78-49ee-b6ab-9dd0812a0517)

**Comment by Dennis40816** [comment]
@JackieesLiao If you follow the [compilation steps outlined](https://iceoryx.io/latest/getting-started/installation/#build-with-cmake), then `iox-roudi` will be located in the `~/iceoryx/build` directory for your case. You must first switch to this directory instead of `~/iceoryx/iceoryx_examples/icehello/build`. You can try again, and if you encounter any issues, feel free to ask further questions :)

**Comment by JackieesLiao** [comment]
@Dennis40816  Thank you. Just now I ran ./iox-roudi in the build in the root directory of iceoryx again, and the problem was solved.
![屏幕截图 2024-01-05 161054](https://github.com/eclipse-iceoryx/iceoryx/assets/88898152/b835e8c8-5e96-48a6-babf-5b757e93a56d)

**Comment by Dennis40816** [comment]
No problem. Have fun with iceoryx :)
