### ISSUE TITLE
High maximum latencies.

### ISSUE THREAD

**Issue by lbm98** [eclipse-iceoryx/iceoryx#2162]
With a small hack i tested some of the maximum latencies in the performance suite,

```c++
    constexpr uint64_t TRANSMISSIONS_PER_ROUNDTRIP{2U};
    auto duration = std::chrono::duration_cast<std::chrono::nanoseconds>(finish - start);
    latencyInNanoSeconds = std::max(latencyInNanoSeconds, static_cast<uint64_t>(duration.count()) / TRANSMISSIONS_PER_ROUNDTRIP);
//        (static_cast<uint64_t>(duration.count()) / (numRoundTrips * TRANSMISSIONS_PER_ROUNDTRIP));
    return iox::units::Duration::fromNanoseconds(latencyInNanoSeconds);
```

and i got back these results

| Payload Size | Maximum Latency [µs] |
|-------------:|---------------------:|
|      16 [B]  |               106816 |
|      32 [B]  |               105956 |
|      64 [B]  |               107391 |
|     128 [B]  |               117026 |
|     256 [B]  |               115382 |
|     512 [B]  |               110566 |
|       1 [kB] |               108231 |
|       2 [kB] |               108247 |
|       4 [kB] |               108340 |
|       8 [kB] |               108298 |
|      16 [kB] |               108342 |
|      32 [kB] |               107609 |
|      64 [kB] |               109656 |
|     128 [kB] |               108702 |
|     256 [kB] |               110803 |
|     512 [kB] |               106641 |
|       1 [MB] |               110513 |
|       2 [MB] |               108845 |
|       4 [MB] |               116433 |

These results are maybe not representative, but i also tested the maximum latencies on the
`client_cxx_waitset.cpp` and `server_cxx_listener.cpp` examples and the latencies were as high as 7000 microseconds.

The average results seemed to be as excpected, around 1 microseconds.
Any thoughts on this?

Thank you very much!

**Comment by elBoberido** [comment]
@lbm98 it's on my todo list for way to long but we need to output an histogram. At least for one chunk size, maybe the largest one, although it does not really matter.

Now to your question. I guess you are not using a realtime operating system. Without a realtime operating system there are no guarantees for how long a process is suspended and then you get the result you measured.

With a realtime OS you get something like here https://github.com/eclipse-iceoryx/iceoryx/discussions/1374#discussioncomment-2877785. The measurements were done with different loads and scheduling priorities.

There are certain limits on what we can do from within iceoryx, e.g. no copies and no context switches to keep the latency low but there is always an OS beneath iceoryx and it also has to fulfill some requirements in order to keep the latency low. One of this requirements is to schedule the process and a non-realtime OS gives one quite poor guarantees in this regard. A realtime OS gives you guarantees for the max time but usually at the cost of an increased min time. What's important is the overhead of the framework and that's what the iceperf example is meant to show. Here we are ~1µs and everything else depends on the OS.

With the Listener and WaitSet more overhead is added since the communication does involve a context switch into the kernel in order to notify the subscriber of the new data. Here we have room for optimization if something like io_uring would be used. Currently we are using semaphores. So the overhead is basically 1µs + the time it takes to trigger the semaphore and the OS to wake up the subscriber process. On the master branch you can use `iceperf-bench-leader -b latency -t iceoryx-cpp-waitset-api` to test the latency with the WaitSet. Keep in mind to build in release mode. On my system the event based latency is around 4-5 times higher than the polling based latency.

Another thing to consider is that the OS puts processes on a deep sleep if they don't utilize the CPU for some time. This can be in the range of only a few 100ms. So if you use events and publish e.g. only once every second, the latency will increase even more since it will take quite a long time for the OS to bring the process back to an operational state. On Linux I once measured around 100µs on average. This is again not caused by the framework but depends on the OS.

The iceperf example is also not ideal to test the max latency. In order to do this we would need to create some CPU load before running the benchmark in order to get the CPU into the performance state. Usually the CPU runs on lower frequencies when there is no or only little load and only after a threshold is reached the OS spins up the frequency. It's possible to improve this a bit by setting the scaling governor to performance. On Linux you can check the scaling governor by `/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` and set it by `echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`. There is quite a high chance the the governor is set to `powersave` by default, especially if you are using a laptop.

I hope this answers your question :)

**Comment by lbm98** [comment]
Yes! Very clearly! Thank you!

I realized i made 2 mistakes:

1. I tested the latencies with manual std::chrono::high_resolution_clock instead of a proper microbenchmark library
the high_resolution_clock can give odd results when it comes to max latency.

2. The processing delay (server side) is several orders or magnitude larger than the communication delay (shared memory)

You may close this (non)-issue :)

**Comment by niclar** [comment]
@elBoberido is there any particular reason to use a kernel semaphore instead of a user space spin lock for the Listener/ WaitSet communication ?

/Best

**Comment by elBoberido** [comment]
@niclar what exactly do you mean with critical section? The semaphore in the Listener/WaitSet is used because the assumption was that it will be triggered every few milliseconds in general. If the frequency is higher, a more sophisticated approach could be taken by spinning for some time before waiting on the semaphore. Up until now, nobody asked for something like this.
