### ISSUE TITLE
The recommended way of having 1 publisher and multiple subscribers

### ISSUE THREAD

**Issue by afpgit** [eclipse-iceoryx/iceoryx#2174]
I would like to first thank you for building this library. 

I went through the example of publisher/subscriber and wanted to know the recommended way of creating 1 publisher and many subscribers. 

As far as I understood, to be able to have N subscribers, we need to create N source codes with N different `constexpr char APP_NAME[]`s. I would appreciate it to have some best practices on this subject using `iceoryx`.

**Comment by elBoberido** [comment]
The `constexpr char APP_NAME[]` is just there to prevent magic values. You need one per process, not per subscriber and you can also use `iox::runtime::PoshRuntime::initRuntime("my-app-name");` instead of the constexpr.

After the `initRuntime` call you can create multiple endpoints like publisher, subscriber, clients, etc. in the same process.

Does this answer your question?

**Comment by afpgit** [comment]
How does this work in terms of scaling the number of subscribers? Does each subscriber need to have a unique app-name? Do I have to create different source codes for each subscriber? 

Let's say I copy the executable associated with `mysubscriber.cpp` into `directory1`,  `directory2`,  `directory3`,  etc. Will they be able to get data from the publisher?

**Comment by elBoberido** [comment]
Yes, they will be be able to get data from a single publisher. You don't even need to copy the application to different directories but just make sure each invocation of the binary creates a new app-name. Can be done by providing a cmd line parameter or you could use `genuid` to generate unique app-names on the fly or use the pid + current time. I would recommend to enable the process monitoring in RouDi (-m ON) if you do this else the resources will not be cleaned up if an app crashes and gets restarted since it will have a different app name.

**Comment by afpgit** [comment]
I did google `genuid` but nothing came up. May I have a link to it to learn more about it?

**Comment by elBoberido** [comment]
Oh, sorry. What I actually meant was `uuidgen` https://www.man7.org/linux/man-pages/man1/uuidgen.1.html

**Comment by afpgit** [comment]
Please correct me if I am wrong. With `./iox-roudi -m ON`, the daemon will force clean up any subscribers that are crashed or peacefully terminated.

**Comment by elBoberido** [comment]
We have a mechanism that each process needs to send a heartbeat to RouDi. If this heartbeat is not send for a longer time, RouDi assumes the application crashed and cleans up the resources thereafter if started with `-m ON`. The cleanup happens only for applications which terminated abnormally, e.g. a crash. Applications which terminated gracefully already cleaned up their resources on their shutdown.

**Comment by elBoberido** [comment]
@afpgit closing the issue. If there are more question feel free to re-open it
