### ISSUE TITLE
Iceoryx support fast-dds

### ISSUE THREAD

**Issue by shenkai9999** [eclipse-iceoryx/iceoryx#2199]
Currently, iceoryx already supports cyclone dds for device to device communication through the gateway. When can fast dds be supported？Because fast dds are also being used by many people,this support is very meaningful！

**Comment by mossmaurice** [comment]
Hi @shenkai9999 Thanks for opening this issue. You are right currently only a gateway [using Cyclone DDS is available](https://github.com/eclipse-iceoryx/iceoryx-gateway-dds). There were some activities to add a gateway using FastDDS a couple of years ago but it never got merged, see here: https://github.com/eclipse-iceoryx/iceoryx/pull/444

Would you have time to contribute a gateway using FastDDS? If so I would suggest creating a separate repository for it like we did for the Cyclone DDS one.

**Comment by SchwarzeMagie** [comment]
Hi  @mossmaurice. I currently have time to contribute a Fast DDS gateway. Should I submit it to the repository: iceoryx-gateway-dds? Is there a specific version requirement for Fast DDS?

**Comment by mossmaurice** [comment]
Hi @SchwarzeMagie Great to hear! :) The iceoryx Cyclone DDS Gateway is still based on an [older commit](https://github.com/eclipse-iceoryx/iceoryx-gateway-dds/blob/main/CMakeLists.txt#L45). I think adding it to the same repository makes sense. However, you might need to rename and restructure things in there a bit so that the user can choose which DDS implementation to use.

> Is there a specific version requirement for Fast DDS?

No, not from my side.

Let me know if you need any help. We can use the chat to discuss any issues: https://gitter.im/eclipse/iceoryx

**Comment by shenkai9999** [comment]
Hello @SchwarzeMagie ,do you have any plans to integrate fast-dds-gateway into iceoryx?

**Comment by SchwarzeMagie** [comment]
Hi @shenkai9999, I plan to make my first code commit this weekend. I still have some details that need to be clarified.

**Comment by SchwarzeMagie** [comment]
Hi @shenkai9999, I'm sorry for the delay in submission due to a sudden change in my work. I have now submitted a merge request with my implemented code to the iceoryx-gateway-dds repository. Please feel free to review it.

**Comment by SchwarzeMagie** [comment]
Hi @mossmaurice, My FastDDS gateway code in the iceoryx-gateway-dds repository has been approved for merging. Could I also submit the FastDDS gateway code to the release_2.0 branch of iceoryx? Because 2.0.x is the version I primarily use now.

**Comment by elBoberido** [comment]
@SchwarzeMagie the 2.0.x branch receives only bugfixes. We want to have a 3.0 release soonish, though

**Comment by SchwarzeMagie** [comment]
> @SchwarzeMagie the 2.0.x branch receives only bugfixes. We want to have a 3.0 release soonish, though

Alright, I understand. Is this issue considered resolved?

**Comment by elBoberido** [comment]
@SchwarzeMagie yes, this can be considered resolved then.

**Comment by mossmaurice** [comment]
@SchwarzeMagie Thanks for your contribution and sorry for my late reply!

We plan to release iceoryx1 v3.0 soon-ish. The only major issue left is https://github.com/eclipse-iceoryx/iceoryx/issues/1295 see [here](https://github.com/orgs/eclipse-iceoryx/projects/1/views/1). I think we'll discuss the details in the next iceoryx developer meetup. Feel free to join.

Once `v3.0` is released we can change these lines here: 

https://github.com/eclipse-iceoryx/iceoryx-gateway-dds/blob/a4a9a9602cca7834a68b1c8c6ae36d00927c4a36/CMakeLists.txt#L45-L46

I hope to use the `v3.0` works in your setup.

**Comment by SchwarzeMagier** [comment]
Hi @mossmaurice ,Thank you very much for your meeting invitation. However, due to the time difference, I might already be resting at that time, and I apologize for that. I would be happy to make modifications and submit them regarding the gateway adaptation requirements after the release of iceoryx 3.0. Thank you.
