### ISSUE TITLE
Question: Multiple Thread Multiple Publisher

### ISSUE THREAD

**Issue by OrenHg** [eclipse-iceoryx/iceoryx#2227]
If i have multiple publisher, each one owns a thread for publish
is that thread safe?
or i should have a big lock for all publishers: lock the big lock before each publisher try to  loan() and publish() ?

**Comment by elfenpiff** [comment]
@OrenHg if you have a setup with multiple threads, where every thread owns its own publisher so that they are not accessed by any other thread, it is safe to use.

The publisher is not thread-safe, but you can use multiple publishers concurrently from multiple processes or from within the same process with multiple threads. 

But you are not allowed to share one publisher with multiple threads and perform concurrent operations on them.

**Comment by elBoberido** [comment]
Closing the issue since the question was answered
