### ISSUE TITLE
MEPOO__MEMPOOL_GETCHUNK_POOL_IS_RUNNING_OUT_OF_CHUNKS

### ISSUE THREAD

**Issue by consolexinhun** [eclipse-iceoryx/iceoryx#2344]
## Brief feature description

how to find ServiceDescription when MEPOO__MEMPOOL_GETCHUNK_POOL_IS_RUNNING_OUT_OF_CHUNKS

## Detailed information

I got error like `MEPOO__MEMPOOL_GETCHUNK_POOL_IS_RUNNING_OUT_OF_CHUNKS`，but i don't known which ServiceDescription lead to this error ？How to find out those ServiceDescriptions

**Comment by consolexinhun** [comment]
I don't want to change the roudi memory pool，i just want to change the publisher or subscriber，but i don't known change which one？

**Comment by elBoberido** [comment]
@consolexinhun unfortunatelly, this is not easily possible with iceoryx1 since many services can share the same mempool.

If you are using a recent version of iceoryx, it should also print the required payload size which would give you a hint on the service description.

You can also check with the introspection app whether the number of used chunks steadily increases, which would indicate a chunk leak. This can usually only happen if you use the untyped API and forget to release a chunk ... of if you collect all the samples in a vector and never release them.
