### ISSUE TITLE
[POPO__CHUNK_SENDER_INVALID_CHUNK_TO_SEND_FROM_USER (code = 58)

### ISSUE THREAD

**Issue by gxl1457628736** [eclipse-iceoryx/iceoryx#2349]
cyclonedds and iceoryx error.why?

**Comment by elfenpiff** [comment]
@gxl1457628736 This is not enough information to start analyzing the bug. Please add all the information that enable us to reproduce the bug so that we can fix it and write a reproducible test that proves that it is fixed.

So we require:
 * A minimalistic setup that caused the bug - with source code if necessary
 * The OS version, iceoryx version, cyclonedds version
 * Actual steps to call to reproduce it

**Comment by elBoberido** [comment]
@gxl1457628736 the error indicates a double free (or nullptr release) of an iceoryx memory chunk. This is an error in an upper layer. In your case this layer seems to be a Cyclone DDS. There is nothing we can do on the iceoryx side.
