### ISSUE TITLE
Mock classes of publisher and subscriber should be derived from base classes

### ISSUE THREAD

**Issue by marthtz** [eclipse-iceoryx/iceoryx#422]
## Brief feature description

Mock classes of publisher and subscriber are currently implemented separately and not related to the original `PublisherPortUser` and `SubscriberPortUser` classes.

## Detailed information

Mock classes of publisher and subscriber should be derived from `PublisherPortUser` and `SubscriberPortUser` classes.
Note: That'll brake some moduletests.

**Comment by elBoberido** [comment]
@mossmaurice no it's not done and this should also not be done since those classes don't have virtual methods. We don't gain anything from deriving from them and make things even worse since we can add methods in the base class and don't notice that we need to adjust the mock. It would only make sense if there would be a base class which defines the interface but that's also not necessary in this case. I would keep it as it is.

**Comment by mossmaurice** [comment]
Ok, thanks closing this issue then
