### ISSUE TITLE
Sparse access control documentation.

### ISSUE THREAD

**Issue by ankitkk** [eclipse-iceoryx/iceoryx#640]
Its not entirely clear how to setup such that iceoryx clients can be under different unix users/groups.  A brief introduction would be helpful. Thanks.

**Comment by elfenpiff** [comment]
@mossmaurice you are currently working on the docu side, do you have time for this topic?

**Comment by elfenpiff** [comment]
I would suggest a short icedelivery based example where we have two publishers A, B and two subscribers X, Y with some groups so that A & X and B & Y are separated and cannot read the data of the non corresponding ports.

**Comment by ankitkk** [comment]
Looking through existing pull requests - Pull request in progress  #630  adds some color to it.

**Comment by elBoberido** [comment]
@ankitkk have a look at this https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/usage-guide.md

It shows how to configure RouDi for multiple user. It's quite long since I tried it, but theoretically you just need to start the application as different user and it should work if there is a segment for that user configured.

**Comment by mossmaurice** [comment]
Thanks @ankitkk for the feedback! We should definitely improve the documentation regarding users and groups.

I've add this point to #482 and will close this issue here. If you think other topics are not covered, please raise them in #482, thanks!
