### ISSUE TITLE
If subscriber's queue is full

### ISSUE THREAD

**Issue by jhx2002** [eclipse-iceoryx/iceoryx#656]
What happen,  If subscriber's queue is full, and the publisher  continues to publish

**Comment by elfenpiff** [comment]
The subscriber queue is actually a circular buffer and whenever it is full the publisher will override the oldest sample with the newest.

Let's say you have the samples [1, 2, 3] in your subscriber queue of capacity 3. After the publisher delivered sample 4 the subscriber queue contains [2, 3, 4].

Currently, we are also working on issue #615 to extend this behavior so that the publisher is blocked when the subscriber queue is full. Our plan is to make this behavior available in the upcoming 1.0 release which comes at the end of this week.

**Comment by elBoberido** [comment]
@jhx2002 is your question sufficiently answered? If yes, please close the issue

**Comment by elBoberido** [comment]
@jhx2002 I assume that the question was sufficiently answered and close this PR. Feel free to open it again if this is not the case.
