### ISSUE TITLE
commmunicate between two nodes  from different docker containers

### ISSUE THREAD

**Issue by jhx2002** [eclipse-iceoryx/iceoryx#899]
How ?

**Comment by elfenpiff** [comment]
@jhx2002 I think we need to add some more detailed documentation for this.

We have a very poorly documented example which should run out of the box (if not it should at least provide some insights): https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_dds/examples

Here I rough draft on how you can accomplish a network communication between iceoryx instances:

1. Create and start two docker containers which are able to communicate via ethernet. You can verify if the network connection is available by typing: `ip addr` look up the IP address of the containers and try to ping them. If this works you are ready to go.
2. Use the iceoryx dds example to setup the icedelivery example so that it communicates between those two docker containers: https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_dds. For this you need to create a config file in `/etc/iceoryx/gateway_config.toml` in each docker container.
3. Add the entry
```
[[services]]
service     = "Radar"
instance    = "FrontLeft"
event       = "Object"
```
to the config file. This is the service description of the publisher of the icedelivery example.

In theory everything should be setup and now you can compile iceoryx with the following commands in both docker containers:
```sh
cmake -Bbuild -Hiceoryx_meta -DEXAMPLES=ON -DDDS_GATEWAY=ON
cd build
make
```

Now open 3 terminals in the first docker container and start the following applications:
* Terminal 1: `./build/iox-roudi`
* Terminal 2: `./build/iceoryx_dds/iox-gw-iceoryx2dds` 
* Terminal 3: `./build/iceoryx_examples/icedelivery/iox-cpp-publisher`
The first docker container is now offering the service in the config file and the iceoryx2dds gateway is publishing them via DDS on the network

Open another 3 terminals in the second docker container and start the following applications:
* Terminal 1: `./build/iox-roudi`
* Terminal 2: `./build/iceoryx_dds/iox-gw-dds2iceoryx`
* Terminal 3: `./build/iceoryx_examples/icedelivery/iox-cpp-subscriber`
The second docker container receives now network messages of the first docker container via DDS and the subscriber should be able to receive them and print them out. The output should be identical to the icedelivery example on a single machine.

**Comment by budrus** [comment]
@elfenpiff should this issue be linked to https://github.com/eclipse-iceoryx/iceoryx/pull/925?
