### ISSUE TITLE
releasing the subscriber after exit main will cause Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qclzdh** [eclipse-iceoryx/iceoryx#972]
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 9.4.0

**Observed result or behaviour:**
application will crash "Segmentation fault (core dumped)"

**Expected result or behaviour:**
no crash happen.

**Conditions where it occurred / Performed steps:**
1. change iceoryx_examples/icehello/iox_subscriber_helloworld.cpp to following code 
 ```bool killswitch = false;
constexpr char APP_NAME[] = "iox-cpp-subscriber-helloworld";


std::shared_ptr<iox::popo::Subscriber<RadarObject>> testSubscriber;

static void sigHandler(int f_sig IOX_MAYBE_UNUSED)
{
    // caught SIGINT or SIGTERM, now exit gracefully
    killswitch = true;
}

int main()
{
    // register sigHandler
    auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
    auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);

    // initialize runtime
    iox::runtime::PoshRuntime::initRuntime(APP_NAME);

    // initialized subscriber
    //iox::popo::Subscriber<RadarObject> subscriber({"Radar", "FrontLeft", "Object"});

    iox::capro::ServiceDescription serviceDescription{"Radar", "FrontLeft", "Object"};
    testSubscriber = std::make_shared<iox::popo::Subscriber<RadarObject>>(serviceDescription);

    std::this_thread::sleep_for(std::chrono::milliseconds(1000));

    //testSubscriber.reset(); // with this line, no crash. Without this line, it will crash      <<---------------<<-------------<<---------<<------------
    return (EXIT_SUCCESS);
}
```

2. run roudi, and run iox-cpp-subscriber-helloworld, and then iox-cpp-subscriber-helloworld will crash
3. one intresting thing is before exit the main, if i add testSubscriber.reset(); , it will work well.

**Comment by elfenpiff** [comment]
@qclzdh The problem here is the following.

* The PoshRuntime must be initialized before you do anything
* The PoshRuntime must be the last living object.

When your application now exits the posh runtime destructor seems to be called first and when the subscriber would like to deregister (with the destruction of the shared_ptr) at the runtime then it is already working on an invalid object.
But if you call `reset` first the subscriber can still deregister at the still valid runtime since we are still in main and everything works.

Is it possible for you to not make the subscriber shared_ptr global? Otherwise you will always run into this issue some way or another since in C++ it is not clearly defined in which order global variables are constructed/destructed.
When you look into the C++ standard you will find something like this:
 1. Globals in a single translation unit are initialized in the order they are defined. 
 2. The initialization order of globals across multiple translation units is unspecified.

The runtime is somehow a global in a different translation unit and therefore this mixup can randomly occur depending on the compiler/version or something else.

But I have to admit that this behavior/bug is somehow also a fault in our design. In the end our posh runtime is a factory for subscriber/publisher but no one really realizes this since it is hidden via a singleton.

**Comment by elfenpiff** [comment]
@qclzdh I fear for the moment we cannot solve this bug easily. We actually have to adjust our design a bit.

But this is a nice example why one should not use singletons ;)

**Comment by qclzdh** [comment]
@elfenpiff  thanks for clarifying how it happenes.  shared_ptr global is only in one special test,  of course I will not use this it.

**Comment by elBoberido** [comment]
@qclzdh `iox::runtime::PoshRuntime::initRuntime` creates a static object in a function, which means it gets destroyed after the end of the scope of the main function. The publisher will also be destroyed afterward. I'm not sure if there is a clear rule about the order of destruction for statics and globals. Theoretically in the inverse order, which implies that the runtime will be destroyed first. The destructor of the subscriber tries to gracefully shut down and de-registers and RouDi. At this point the runtime is already destroyed and the crash happens.

If you want to use the global and still ensure that the object is deleted before the runtime, you can use the `iox::cxx::makeScopedStatic`. The naming is poor since this can not only be used for statics but also for global variables and should maybe be named `makeScopeGuard`. The value must be in a container which has an `emplace` and a `reset` method, like the `iox::cxx::optional`. With this, you can have something like

```cpp
constexpr char APP_NAME[] = "iox-cpp-subscriber-helloworld";

iox::cxx::optional<iox::popo::Subscriber<RadarObject>> testSubscriber;

static void sigHandler(int f_sig IOX_MAYBE_UNUSED)
{
   // caught SIGINT or SIGTERM, now exit gracefully
   killswitch = true;
}

int main()
{
   // register sigHandler
   auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
   auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);

   // initialize runtime
   iox::runtime::PoshRuntime::initRuntime(APP_NAME);

   // initialized subscriber
   //iox::popo::Subscriber<RadarObject> subscriber({"Radar", "FrontLeft", "Object"});

   iox::capro::ServiceDescription serviceDescription{"Radar", "FrontLeft", "Object"};
   testSubscriberScopeGuard = iox::cxx::makeScopedStatic(&testSubscriber, serviceDescription);

   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
   return (EXIT_SUCCESS);
}
``

**Comment by qclzdh** [comment]
@elBoberido thanks for the advise, a good way to release the resource before exit main while using global variable.
