### ISSUE TITLE
Performance of DDS over Iceoryx

### ISSUE THREAD

**Issue by hemalbavishi** [eclipse-iceoryx/iceoryx#974]
I have following questions w.r.t. Iceoryx over DDS

1. When to use DDS and When to use Iceoryx ?
2. Are there any better performance of Iceoryx over DDS?

It would be great if you could thrown some light on this.

Many thanks!

Best Regards,
Hemal Bavishi

**Comment by elfenpiff** [comment]
@hemalbavishi 

> When to use DDS and When to use Iceoryx ?

If you are communicating between processes on a single machine, you should use iceoryx since here you use the zero copy performance boost by default.

If you would like to communicate between processes in a network I would tend to use DDS. This should work without any configuration right out of the box, but you would loose the zero copy performance boost - depending on what DDS implementation you use.
But you could also use iceoryx in this case. With this approach you would get the zero copy performance boost when you are communicating with local processes and when you are communicating with a different iceoryx instance over the network we serialize the data stream into dds and communicate via a gateway with this other iceoryx instance. This would require some configuration which is described here: https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_dds
But keep in mind with this approach other DDS participants would only receive the iceoryx byte stream on the topics since the gateway connects multiple iceoryx instances and is not a generic DDS service.

> Are there any better performance of Iceoryx over DDS?

Iceoryx uses a zero copy inter process communication mechanism and this is as fast as you can get when you are on a single machine. But since it requires a common shared memory between all the processes this approach is not so easy implementable for a network communication.

Summary:
1. One machine, inter process communication: Use iceoryx.
2. Network Communication: DDS easiest, iceoryx also possible with inter process communication boost but requires a little bit of configuration.

**Comment by elfenpiff** [comment]
@hemalbavishi 

Another criteria you may want to look at is the code quality, test coverage, stability and especially documentation. What brings the fastest library when it contains bugs and you end up in an endless crunch circle where you have to fix issues not caused by your software but by someone else's faulty library.

Our plan for iceoryx is to get it certified soon and we have already a lot of concepts, tests and idioms in place to ensure a high code quality.

Just take a look at our testing guide: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
or our error handling concept: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/how-optional-and-error-values-are-returned-in-iceoryx.md
or our examples which describe a lot of features in detail.

When you choose the library which suits your needs best maybe take also look if there are similar concepts and examples in place and if they would like to certify there code too. Those can be useful indicators to make your job a little bit more easy.

**Comment by hemalbavishi** [comment]
@elfenpiff 

Thank you for your detailed explanation. I did not put my questions in a right way. I know Iceoryx is more suitable for IPC whereas DDS is more suitable for Network Communication. I am wondering whether I can use DDS for IPC (e.g. I can use SOME/IP for IPC as well network communication)? If so, what would be the performance of Iceoryx IPC over DDS IPC. I know it's bit open question and it might be implementation specific but in general I would like to know.

**Comment by elfenpiff** [comment]
@hemalbavishi If you only would like to do IPC communication then I suggest iceoryx.

SomeIP and DDS implementation most likely will use sockets to transfer the data package. So lets say you send an image of 1MB to two receiving applications. The sender will copy it locally from the camera to some internal storage and then twice to the sockets of each application. And copying data is a time consuming process for the cpu (take a look at the chart: https://gist.github.com/jboner/2841832 and look for main memory reference to get an idea in comparision to L1 and L2 cache).
So the best way of increasing the performance is to follow a zero copy approach instead of performing 3 unnecessary copies.

With iceoryx all processes share a common memory segment. This means when the sender would like to acquire an image from the camera it acquires a chunk of memory from iceoryx, the camera writes the data into the acquired chunk directly and then the sender delivers a pointer to that data to the two receiving applications. So instead of copying the data 3 times you write the data directly into the shared memory and distribute the pointer to that data which is way more efficient. And the bigger the data gets the more efficient is iceoryx.
We have a nearly constant latency independent of the data size. DDS and SomeIP latency will usually increase massively with increasing data size and number of receivers.

**Comment by elBoberido** [comment]
@hemalbavishi Cyclone DDS optionally (compile time switch by default on, runtime switch by default off) uses iceoryx for local transport. So you get what you would get from iceoryx plus additional latency and memory usage since that layer needs additional CPU cycles and does additional caching. Depending on your needs, you would have additional QoS, etc from the DDS world.

**Comment by hemalbavishi** [comment]
@elBoberido 
Thank you for your quick response. One of the advantage as you rightly mentioned with DDS world is additional QoS parameter which Iceoryx doesn't support as of now. Nevertheless, my question is answered hence I am closing this ticket.
